// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: buildrequest/buildrequest.proto

package buildrequest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BuildRequestService_CreateBuildRequestMethod_FullMethodName = "/buildrequest.BuildRequestService/CreateBuildRequestMethod"
)

// BuildRequestServiceClient is the client API for BuildRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type BuildRequestServiceClient interface {
	CreateBuildRequestMethod(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*CreateBuildRespone, error)
}

type buildRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildRequestServiceClient(cc grpc.ClientConnInterface) BuildRequestServiceClient {
	return &buildRequestServiceClient{cc}
}

func (c *buildRequestServiceClient) CreateBuildRequestMethod(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*CreateBuildRespone, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBuildRespone)
	err := c.cc.Invoke(ctx, BuildRequestService_CreateBuildRequestMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildRequestServiceServer is the server API for BuildRequestService service.
// All implementations must embed UnimplementedBuildRequestServiceServer
// for forward compatibility.
//
// Service definition
type BuildRequestServiceServer interface {
	CreateBuildRequestMethod(context.Context, *CreateBuildRequest) (*CreateBuildRespone, error)
	mustEmbedUnimplementedBuildRequestServiceServer()
}

// UnimplementedBuildRequestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildRequestServiceServer struct{}

func (UnimplementedBuildRequestServiceServer) CreateBuildRequestMethod(context.Context, *CreateBuildRequest) (*CreateBuildRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBuildRequestMethod not implemented")
}
func (UnimplementedBuildRequestServiceServer) mustEmbedUnimplementedBuildRequestServiceServer() {}
func (UnimplementedBuildRequestServiceServer) testEmbeddedByValue()                             {}

// UnsafeBuildRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildRequestServiceServer will
// result in compilation errors.
type UnsafeBuildRequestServiceServer interface {
	mustEmbedUnimplementedBuildRequestServiceServer()
}

func RegisterBuildRequestServiceServer(s grpc.ServiceRegistrar, srv BuildRequestServiceServer) {
	// If the following call pancis, it indicates UnimplementedBuildRequestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildRequestService_ServiceDesc, srv)
}

func _BuildRequestService_CreateBuildRequestMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildRequestServiceServer).CreateBuildRequestMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildRequestService_CreateBuildRequestMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildRequestServiceServer).CreateBuildRequestMethod(ctx, req.(*CreateBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildRequestService_ServiceDesc is the grpc.ServiceDesc for BuildRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "buildrequest.BuildRequestService",
	HandlerType: (*BuildRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBuildRequestMethod",
			Handler:    _BuildRequestService_CreateBuildRequestMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buildrequest/buildrequest.proto",
}
